<form action="weather/posted" method="post">
    <label for="city">City:</label><br>
    <input type="text" id="city" name="city"><br><br>
    <table>
        <thead>
        <tr>
            <th>Date/Time</th>
            <th>Weather</th>
            <th>Wind</th>
            <th>Temperature</th>
            <th>Cloud</th>
            <th>Humidity</th>
            <th>Pressure</th>
        </tr>

            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>


            </tr>

        </thead>
    </table>
    <input type="submit" value="Submit">
</form>
