<?php
/** @var Tsintsadze\WeatherApp\Block\Weather $block */

$city = $block->getCity();
?>


<style>
    th {
        font-size: 10px;
    }

    td {
        font-size: 10px;
    }

    th, td {
        padding: 2px;
    }

    table, th, td {
        border: 1px solid;
        border-collapse: collapse;
    }
    label {
        font-size: 20px;
    }
    ul {
        padding-left: 20px;
    }
</style>
<h1><?= __("Weather in your city.") ?></h1>
<form action="<?= $block->getPostUrl()?>" method="post">
    <label for="city">
        <?= __("CITY") ?>
    </label>
    <input type="text" id="city" name="city">
    <button>submit</button>
</form>
<div>
    <ul>
        <li>City: </li>
        <li>Country: <?= $block->getCountry()?></li>
        <li>Description: </li>
        <li>Temperature (°C): </li>
        <li>Feels Like (°C): </li>
        <li>Pressure (hPa): </li>
        <li>Humidity (%): </li>
        <li>Wind Speed (meter/sec): </li>
        <li>Sunrise (UTC): </li>
        <li>Sunset (UTC): </li>
    </ul>
</div>
