<style>
    th {
        font-size: 10px;
    }

    td {
        font-size: 10px;
    }

    th, td {
        padding: 2px;
    }

    table, th, td {
        border: 1px solid;
        border-collapse: collapse;
    }
    label {
        font-size: 20px;
    }
    ul {
        padding-left: 20px;
    }
</style>
<h1>Weather in your city.</h1>
<form action="/weather/posted/posted" method="post">
    <label for="city">
        city
    </label>
    <input type="text" id="city" name="city">
    <button>submit</button>
</form>
<table>
    <ul>
        <li>City: </li>
        <li>Country:  </li>
        <li>Description: </li>
        <li>Temperature (°C): </li>
        <li>Feels Like (°C): </li>
        <li>Pressure (hPa): </li>
        <li>Humidity (%): </li>
        <li>Wind Speed (meter/sec): </li>
        <li>Sunrise (UTC): </li>
        <li>Sunset (UTC): </li>
    </ul>
</table>
